[project]
name = "vehicle-api"
version = "0.1.0"
description = "A Python API for vehicle data management"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.116.1",
    "sqlalchemy>=2.0.43",
    "uuid-utils>=0.11.0",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.21.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.1.0",
    "ruff>=0.12.12",
    "ty>=0.0.1a20",
]
