class ArgumentException(Exception): ...


class ArgumentTypeMismatch(ArgumentException): ...


class ArgumentNull(ArgumentException): ...


class ArgumentNullOrEmpty(ArgumentException): ...


class ArgumentNullOrWhiteSpace(ArgumentException): ...
