[tool.poetry]
name = "application"
version = "0.1.0"
description = "Application layer of vehicle-api"
authors = ["mbalzert@gmail.com"]
packages = [
    { include = "application" }
]

[tool.poetry.dependencies]
python = "^3.10"
domain = { path = "../domain" }
